import { Venue, CommunityStats, UserProfile } from './types';

export const mockRestaurants: Venue[] = [
  {
    id: 'r1',
    type: 'restaurant',
    name: 'Le Bernardin',
    city: 'New York',
    neighborhood: 'Midtown',
    cuisine: 'French Seafood',
    cuisineTags: ['French', 'Seafood', 'Fine Dining'],
    priceLevel: 4,
    compositeScore: 94,
    rank: 1,
    sourceRatings: [
      { source: 'Michelin', rating: '3 Stars' },
      { source: 'The Infatuation', rating: '9.4' },
      { source: 'Eater', rating: 'Essential' },
      { source: 'Google', rating: '4.7' },
    ],
    latitude: 40.7615,
    longitude: -73.9814,
    address: '155 W 51st St, New York, NY',
  },
  {
    id: 'r2',
    type: 'restaurant',
    name: 'Tatiana',
    city: 'New York',
    neighborhood: 'Lincoln Center',
    cuisine: 'Caribbean-American',
    cuisineTags: ['Caribbean', 'American', 'Creative'],
    priceLevel: 3,
    compositeScore: 91,
    rank: 2,
    sourceRatings: [
      { source: 'Michelin', rating: '1 Star' },
      { source: 'The Infatuation', rating: '9.1' },
      { source: 'Eater', rating: 'Essential' },
      { source: 'Beli', rating: '4.8' },
    ],
    latitude: 40.7725,
    longitude: -73.9835,
    address: '10 Lincoln Center Plaza, New York, NY',
  },
  {
    id: 'r3',
    type: 'restaurant',
    name: 'Don Angie',
    city: 'New York',
    neighborhood: 'West Village',
    cuisine: 'Italian-American',
    cuisineTags: ['Italian', 'American', 'Pasta'],
    priceLevel: 3,
    compositeScore: 87,
    rank: 3,
    sourceRatings: [
      { source: 'Michelin', rating: '1 Star' },
      { source: 'The Infatuation', rating: '8.9' },
      { source: 'Beli', rating: '4.7' },
      { source: 'Google', rating: '4.6' },
    ],
    latitude: 40.7328,
    longitude: -74.0027,
    address: '103 Greenwich Ave, New York, NY',
  },
  {
    id: 'r4',
    type: 'restaurant',
    name: 'Thai Diner',
    city: 'New York',
    neighborhood: 'Nolita',
    cuisine: 'Thai',
    cuisineTags: ['Thai', 'Diner', 'Casual'],
    priceLevel: 2,
    compositeScore: 78,
    rank: 4,
    sourceRatings: [
      { source: 'The Infatuation', rating: '8.2' },
      { source: 'Eater', rating: 'Heatmap' },
      { source: 'Beli', rating: '4.5' },
      { source: 'Google', rating: '4.4' },
    ],
    latitude: 40.7223,
    longitude: -73.9953,
    address: '186 Mott St, New York, NY',
  },
  {
    id: 'r5',
    type: 'restaurant',
    name: "Joe's Pizza",
    city: 'New York',
    neighborhood: 'Greenwich Village',
    cuisine: 'Pizza',
    cuisineTags: ['Pizza', 'Casual', 'Late Night'],
    priceLevel: 1,
    compositeScore: 72,
    rank: 5,
    sourceRatings: [
      { source: 'The Infatuation', rating: '7.8' },
      { source: 'Beli', rating: '4.3' },
      { source: 'Google', rating: '4.5' },
      { source: 'Reddit', rating: 'Highly Rec' },
    ],
    latitude: 40.7306,
    longitude: -74.0021,
    address: '7 Carmine St, New York, NY',
  },
  {
    id: 'r6',
    type: 'restaurant',
    name: 'Dhamaka',
    city: 'New York',
    neighborhood: 'Lower East Side',
    cuisine: 'Indian',
    cuisineTags: ['Indian', 'Regional', 'Spicy'],
    priceLevel: 2,
    compositeScore: 85,
    rank: 6,
    sourceRatings: [
      { source: 'Michelin', rating: 'Bib Gourmand' },
      { source: 'The Infatuation', rating: '8.7' },
      { source: 'Eater', rating: 'Essential' },
      { source: 'Google', rating: '4.5' },
    ],
    latitude: 40.7185,
    longitude: -73.9881,
    address: '119 Delancey St, New York, NY',
  },
];

export const mockHotels: Venue[] = [
  {
    id: 'h1',
    type: 'hotel',
    name: 'The Mark',
    city: 'New York',
    neighborhood: 'Upper East Side',
    amenityTags: ['Spa', 'Rooftop', 'Luxury'],
    priceLevel: 4,
    compositeScore: 92,
    rank: 1,
    sourceRatings: [
      { source: 'Condé Nast', rating: 'Gold List' },
      { source: 'Google', rating: '4.6' },
    ],
    latitude: 40.7770,
    longitude: -73.9624,
    address: '25 E 77th St, New York, NY',
  },
  {
    id: 'h2',
    type: 'hotel',
    name: 'The Ned NoMad',
    city: 'New York',
    neighborhood: 'NoMad',
    amenityTags: ['Rooftop Bar', 'Restaurant', 'Boutique'],
    priceLevel: 3,
    compositeScore: 86,
    rank: 2,
    sourceRatings: [
      { source: 'Condé Nast', rating: 'Hot List' },
      { source: 'Google', rating: '4.5' },
    ],
    latitude: 40.7453,
    longitude: -73.9882,
    address: '1170 Broadway, New York, NY',
  },
  {
    id: 'h3',
    type: 'hotel',
    name: 'Aman New York',
    city: 'New York',
    neighborhood: 'Midtown',
    amenityTags: ['Spa', 'Pool', 'Ultra Luxury', 'Restaurant'],
    priceLevel: 4,
    compositeScore: 95,
    rank: 3,
    sourceRatings: [
      { source: 'Condé Nast', rating: 'Gold List' },
      { source: 'Google', rating: '4.4' },
    ],
    latitude: 40.7616,
    longitude: -73.9745,
    address: '730 5th Ave, New York, NY',
  },
  {
    id: 'h4',
    type: 'hotel',
    name: 'The Ludlow',
    city: 'New York',
    neighborhood: 'Lower East Side',
    amenityTags: ['Boutique', 'Rooftop', 'Trendy'],
    priceLevel: 2,
    compositeScore: 74,
    rank: 4,
    sourceRatings: [
      { source: 'Google', rating: '4.3' },
    ],
    latitude: 40.7206,
    longitude: -73.9882,
    address: '180 Ludlow St, New York, NY',
  },
];

export const mockCommunityStats: Record<string, CommunityStats> = {
  r1: {
    venueId: 'r1',
    goBackCount: 342,
    iffyCount: 28,
    wouldNotCount: 5,
    aiSummary: 'Widely regarded as the best seafood in NYC. Impeccable service and transcendent fish dishes.',
    topDishes: ['Lobster Tartare', 'Barely Cooked Salmon', 'Thinly Pounded Yellowfin Tuna'],
    highlights: ['Special occasion worthy', 'Jacket required', 'Book 3+ weeks ahead'],
  },
  r3: {
    venueId: 'r3',
    goBackCount: 215,
    iffyCount: 42,
    wouldNotCount: 12,
    aiSummary: 'Creative Italian-American with the famous chrysanthemum toast. Cozy Village vibes.',
    topDishes: ['Chrysanthemum Toast', 'Pinwheel Lasagna', 'Funfetti Cake'],
    highlights: ['Hard reservation', 'Great date spot', 'Walk-ins at bar'],
  },
};

export const mockUser: UserProfile = {
  id: 'u1',
  name: 'Mikhail',
  reviewCount: 23,
  listsCount: 5,
};

export const allMockVenues = [...mockRestaurants, ...mockHotels];
